// <auto-generated />
using System.Reflection;

[assembly: AssemblyVersion("1.0.0.2340")]
[assembly: AssemblyFileVersion("1.0.0.2340")]
[assembly: AssemblyInformationalVersion("1.0.0.2340")]

namespace Yagu;

internal static class AppInfo
{
    public const string Name = "Yagu";
    public const string Description = "Yet Another Grep Utility";
    public const string Version = "1.0.0.2340";
    public const string WindowTitle = "Yagu - Yet Another Grep Utility 1.0.0.2340";
}