<#
    add-license-headers.ps1

    Prepends the GPL-3.0 license header to every first-party source file
    (.cs, .rs, .xaml). Idempotent (skips files that already carry the header),
    encoding-preserving (keeps each file's UTF-8 BOM state and newline style),
    and it never touches vendored code, build output, or generated files.

    Usage:
        pwsh -File scripts/add-license-headers.ps1            # apply
        pwsh -File scripts/add-license-headers.ps1 -DryRun    # report only
#>
[CmdletBinding()]
param(
    [string]$Root = (Split-Path -Parent $PSScriptRoot),
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

# Em-dash injected by code point so this script stays pure-ASCII (Windows
# PowerShell 5.1 mis-decodes a literal U+2014 in an ANSI-read .ps1).
$emdash  = [char]0x2014
$program = "Yagu $emdash Yet Another Grep Utility"
$holder  = 'the Yagu author (github.com/andrewtheart)'
$year    = '2025-2026'

# The license notice, one entry per line (empty string = blank line).
$notice = @(
    $program,
    "Copyright (C) $year $holder",
    '',
    'This program is free software: you can redistribute it and/or modify',
    'it under the terms of the GNU General Public License as published by',
    'the Free Software Foundation, either version 3 of the License, or',
    '(at your option) any later version.',
    '',
    'This program is distributed in the hope that it will be useful,',
    'but WITHOUT ANY WARRANTY; without even the implied warranty of',
    'MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the',
    'GNU General Public License for more details.',
    '',
    'You should have received a copy of the GNU General Public License',
    'along with this program.  If not, see <https://www.gnu.org/licenses/>.'
)

function Build-BlockComment([string]$nl) {
    # C-style /* ... */ block for .cs and .rs.
    $sb = "/*$nl"
    foreach ($line in $notice) {
        $sb += if ($line -eq '') { " *$nl" } else { " * $line$nl" }
    }
    $sb + " */$nl"
}

function Build-XmlComment([string]$nl) {
    # XML <!-- ... --> block for .xaml (the notice contains no '--').
    $sb = "<!--$nl"
    foreach ($line in $notice) {
        $sb += if ($line -eq '') { $nl } else { "  $line$nl" }
    }
    $sb + "-->$nl"
}

function Test-Excluded([string]$p) {
    return ($p -match '\\(bin|obj|node_modules)\\') -or
           ($p -match '\\src\\vendor\\') -or
           ($p -match '\\TestResults\\') -or
           ($p -match '\.g\.cs$') -or
           ($p -match '\.g\.i\.cs$') -or
           ($p -match '\.Designer\.cs$') -or
           ($p -match 'AssemblyInfo\.cs$') -or
           ($p -match '\.AssemblyAttributes\.cs$') -or
           ($p -match 'GlobalUsings') -or
           ($p -match 'AppInfo\.g\.cs$')
}

$targets = Get-ChildItem $Root -Recurse -File -Include '*.cs', '*.rs', '*.xaml' -ErrorAction SilentlyContinue |
    Where-Object { -not (Test-Excluded $_.FullName) }

$added = 0; $skippedHeader = 0; $skippedGenerated = 0
foreach ($file in $targets) {
    $bytes = [System.IO.File]::ReadAllBytes($file.FullName)
    $hasBom = ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF)
    $text = [System.Text.Encoding]::UTF8.GetString($bytes)
    if ($hasBom) { $text = $text.TrimStart([char]0xFEFF) }

    $head = if ($text.Length -gt 1000) { $text.Substring(0, 1000) } else { $text }
    if ($head -match 'GNU General Public License') { $skippedHeader++; continue }
    if ($head -match '<auto-generated') { $skippedGenerated++; continue }

    $nl = if ($text.Contains("`r`n")) { "`r`n" } else { "`n" }

    if ($file.Extension -eq '.xaml') {
        $header = Build-XmlComment $nl
        $idx = $text.IndexOf('?>')
        if ($text.StartsWith('<?xml') -and $idx -ge 0) {
            $declEnd = $idx + 2
            $decl = $text.Substring(0, $declEnd)
            $rest = $text.Substring($declEnd).TrimStart("`r", "`n")
            $newText = $decl + $nl + $header + $nl + $rest
        }
        else {
            $newText = $header + $nl + $text
        }
    }
    else {
        $header = Build-BlockComment $nl
        $newText = $header + $nl + $text
    }

    if ($DryRun) { $added++; continue }
    $enc = New-Object System.Text.UTF8Encoding($hasBom)
    [System.IO.File]::WriteAllText($file.FullName, $newText, $enc)
    $added++
}

$verb = if ($DryRun) { 'WOULD add' } else { 'Added' }
Write-Host "$verb header to $added file(s); skipped $skippedHeader already-headered, $skippedGenerated generated."
