#requires -Version 5.1
<#
.SYNOPSIS
    Generates the build-time TelemetryConfig partial that carries the real proxy endpoint + app token.

.DESCRIPTION
    Invoked by Yagu.csproj (target GenerateYaguTelemetryConfig) ONLY when a real proxy URL is supplied
    via Yagu/telemetry.local.props (gitignored) or the YAGU_PROXY_URL/YAGU_APP_TOKEN environment
    variables. Writes a `public static partial class TelemetryConfig` with the real ProxyBaseUrl and
    AppToken into an obj/ (gitignored) file, which the build compiles INSTEAD of the committed
    offline placeholder (TelemetryConfig.Defaults.cs). The real values are never committed to source.

    ASCII-only by design so it parses identically under Windows PowerShell 5.1 and pwsh.
#>
param(
    [Parameter(Mandatory = $true)][string]$ProxyUrl,
    [string]$AppToken = '',
    [Parameter(Mandatory = $true)][string]$OutputFile
)

$ErrorActionPreference = 'Stop'

function ConvertTo-CSharpStringLiteral([string]$value) {
    if ($null -eq $value) { return '' }
    return $value.Replace('\', '\\').Replace('"', '\"')
}

$urlLiteral = ConvertTo-CSharpStringLiteral $ProxyUrl
$tokenLiteral = ConvertTo-CSharpStringLiteral $AppToken

$content = @"
// <auto-generated />
// Generated by scripts/generate-telemetry-config.ps1 from Yagu/telemetry.local.props or the
// YAGU_PROXY_URL / YAGU_APP_TOKEN environment variables. DO NOT COMMIT: this file carries the real
// proxy endpoint and app token. It lives under obj/ (gitignored) and is regenerated on every build.
namespace Yagu.Services.Telemetry;

public static partial class TelemetryConfig
{
    public const string ProxyBaseUrl = "$urlLiteral";
    public const string AppToken = "$tokenLiteral";
}
"@

$directory = Split-Path -Parent $OutputFile
if ($directory -and -not (Test-Path -LiteralPath $directory)) {
    New-Item -ItemType Directory -Path $directory -Force | Out-Null
}

# Only rewrite when the content actually changed, so incremental/design-time builds don't churn.
if ((Test-Path -LiteralPath $OutputFile) -and ((Get-Content -LiteralPath $OutputFile -Raw) -eq $content)) {
    exit 0
}

Set-Content -LiteralPath $OutputFile -Value $content -Encoding UTF8
Write-Host "Generated telemetry config -> $OutputFile (ProxyBaseUrl configured)"
