param(
  [Parameter(Mandatory = $true)]
  [string]$VersionFile,

  [Parameter(Mandatory = $true)]
  [string]$OutputFile
)

$ErrorActionPreference = 'Stop'

$versionDir = Split-Path -Parent $VersionFile
if (-not [string]::IsNullOrWhiteSpace($versionDir)) {
  [IO.Directory]::CreateDirectory($versionDir) | Out-Null
}

$current = '1.0.0.0'
if (Test-Path -LiteralPath $VersionFile) {
  $read = [IO.File]::ReadAllText($VersionFile).Trim()
  if (-not [string]::IsNullOrWhiteSpace($read)) {
    $current = $read
  }
}

try {
  $parsed = [Version]$current
} catch {
  $parsed = [Version]'1.0.0.0'
}

$major = [Math]::Max(0, $parsed.Major)
$minor = [Math]::Max(0, $parsed.Minor)
$build = if ($parsed.Build -ge 0) { $parsed.Build } else { 0 }
$revision = if ($parsed.Revision -ge 0) { $parsed.Revision } else { 0 }

$revision++
if ($revision -gt 65535) {
  $revision = 0
  $build++
}
if ($build -gt 65535) {
  $build = 0
  $minor++
}
if ($minor -gt 65535) {
  $minor = 0
  $major++
}

$newVersion = "$major.$minor.$build.$revision"
[IO.File]::WriteAllText($VersionFile, $newVersion, [Text.UTF8Encoding]::new($false))

$outputDir = Split-Path -Parent $OutputFile
if (-not [string]::IsNullOrWhiteSpace($outputDir)) {
  [IO.Directory]::CreateDirectory($outputDir) | Out-Null
}

$source = @"
// <auto-generated />
using System.Reflection;

[assembly: AssemblyVersion("$newVersion")]
[assembly: AssemblyFileVersion("$newVersion")]
[assembly: AssemblyInformationalVersion("$newVersion")]

namespace Yagu;

internal static class AppInfo
{
    public const string Name = "Yagu";
    public const string Description = "Yet Another Grep Utility";
    public const string Version = "$newVersion";
    public const string WindowTitle = "Yagu - Yet Another Grep Utility $newVersion";
}
"@

[IO.File]::WriteAllText($OutputFile, $source, [Text.UTF8Encoding]::new($false))
Write-Host "Yagu version $newVersion"
